name: Release Changelog
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Normalize commit messages
        run: |
          chmod +x .github/scripts/normalize-commits.sh
          ./.github/scripts/normalize-commits.sh ${{ github.event.before }} > normalized_commits.txt
          
      - name: Generate CHANGELOG
        run: |
          npx -y conventional-changelog-cli@4.0.0 -p angular \
            --release-count 0 \
            --out-file CHANGELOG.md \
            --context "$(jq -n --rawfile commits normalized_commits.txt '{"commits": $commits}')"
            
      - name: Build osu.syn.server
        working-directory: 'osu!syn.server'
        run: |
          chmod +x build.sh
          ./build.sh
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          body: file://CHANGELOG.md
          
      - name: Upload Server Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: 'osu!syn.server/build/osu_sync_server'
          asset_name: osu_sync_server_${{ github.ref_name }}_linux
          asset_content_type: application/octet-stream
