name: Release Changelog
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Normalize commit messages
        run: |
          chmod +x .github/scripts/normalize-commits.sh
          ./.github/scripts/normalize-commits.sh ${{ github.event.before }} > normalized_commits.txt
          
      - name: Generate CHANGELOG
        run: |
          npx -y conventional-changelog-cli@4.0.0 -p angular \
            --release-count 0 \
            --out-file CHANGELOG.md \
            --context "$(jq -n --rawfile commits normalized_commits.txt '{"commits": $commits}')"
            
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          body: file://CHANGELOG.md
